### ISSUE TITLE
[FEATURE] You should collect shift and marks data of students who use the website

### ISSUE THREAD

**Issue by pritam42069** [timepassuser/Jee-Mains-Marks-Calculator#11]
You should collect the shift and marks data of students who use the website and their application number as a unique ID, then make something to predict their percentile. 
Couldn't find any other way to request this feature, feel free to delete this. Good work btw

**Comment by timepassuser** [comment]
I do want to do this, however i feel like it would be invading people's privacy, so I'm not sure whether I should go for it.

**Comment by pritam42069** [comment]
It could always be anonymous, it would feel like invading privacy if you stored their application number, so instead generate unique codes for the application numbers and store it in the database with their marks. I don't think people would mind, and there could be an option to opt out. I would be willing to help out with this but I have NEET soon :(

**Comment by timepassuser** [comment]
Oh I see, that's a shame! Collaborating might've been fun. I will see if i can implement this, will need to use a database, right now the response sheet is just fetched from a cloudflare worker so cloudflare's database might work, hopefully its free.
