### ISSUE TITLE
Show questions that have been dropped

### ISSUE THREAD

**Issue by NitishKanna107** [timepassuser/Jee-Mains-Marks-Calculator#12]
Hey,
I really appreciate the work that you have been doing. I would like to know if you have got 8th April shift 2 question paper or response sheet. I didn't download mine for some silly reason. I figured out that the answer to a question in Chemistry has been changed (looked at the commit history) but would like to know what exactly that question is. Please help me out.
Cheers, 
Nitish

**Comment by timepassuser** [comment]
Hmm,  I don't have individual response sheets and questions. The website just fetches them from your response sheet link to display it to you.
If you accessed it before it might be saved in your browser history, try searching for cdn3 in your history.
If not present.. sorry i can't really help you more than that. Try searching on the internet for 8s2 response sheets or ask someone to lend you there's.

**Comment by NitishKanna107** [comment]
Hey, thanks for responding. I had recently deleted my browsing history so I don't think I can get the link from there. I thought that the links we put in were probably saved somewhere but looks like they aren't. Anyways, I will consider recovering my browsing history to get my response sheet link.

**Comment by timepassuser** [comment]
Yup, good luck
