### ISSUE TITLE
Something brokey, nothing shows up now

### ISSUE THREAD

**Issue by DevBoiAgru** [timepassuser/Jee-Mains-Marks-Calculator#3]
![image](https://github.com/timepassuser/Jee-Mains-Marks-Calculator/assets/79085233/a143faea-828a-416d-b683-be45a1228e65)

From what i know:

in these lines:
![image](https://github.com/timepassuser/Jee-Mains-Marks-Calculator/assets/79085233/5f6a1143-48f9-48b3-a806-fd4a8d11529c)
`responses[questionId][1]` is returning null, and there is nothing associated with null in subjectTables (line 165), which makes the whole subjectTable null and it throws an error when trying to insert a row.
I tried hardcoding it to `subjectTable = subjectTables["MA"]` and it worked (added all questions to the maths table), so I'm guessing it cannot get the table to add the rows to

**Comment by timepassuser** [comment]
Hm, Im not sure what you are talking about since it is working for me. Are you sure you're selecting the correct file? The image you've uploaded shows answerkeys.html, but you're supposed to upload the response sheet

**Comment by DevBoiAgru** [comment]
Just checked, looks like its just unconsistent for some reason with that exact file, sometimes works, sometimes doesnt. Downloaded the original .html from nta again and it worked. Might add some warnings and pop ups to let the user know the file is broken lol
