### ISSUE TITLE
download as pdf takes to print the pdf

### ISSUE THREAD

**Issue by ghost** [timepassuser/Jee-Mains-Marks-Calculator#4]
clicking on download pdf takes me to printing window. its tho its still possible to download as a html file.

**Comment by timepassuser** [comment]
Well yes clicking on download pdf is supposed to take you to the printing window, so it's as expected. I don't understand what issue you are having. Could you elaborate?

**Comment by timepassuser** [comment]
Well once it starts printing there is an option to save as pdf. You can try it on any webpage, just press ctrl+p, then there is a way to save the webpage as a pdf. On firefox and chrome atleast, im not sure about edge
