### ISSUE TITLE
New response sheet has different format

### ISSUE THREAD

**Issue by Prakul2006** [timepassuser/Jee-Mains-Marks-Calculator#8]
![Screenshot 2024-04-13 at 1 36 52 AM](https://github.com/timepassuser/Jee-Mains-Marks-Calculator/assets/68892747/eba63fcb-df78-4431-b200-baaa1724ebab)

**Comment by Prakul2006** [comment]
fixed
replace
`function getAnskey(responsecontent) {
    // var e = document.createElement("html");  // BAD method, don't ever use
    // e.innerHTML = responsecontent;
    // This is the correct way
    parser = new DOMParser()
    e = parser.parseFromString(responsecontent, "text/html");
    table = e.getElementsByClassName("main-info-pnl")[0].children[2].children[0]
    date = table.children[3].children[1].innerText
    time = table.children[4].children[1].innerText`
with 
`function getAnskey(responsecontent) {
    // var e = document.createElement("html");  // BAD method, don't ever use
    // e.innerHTML = responsecontent;
    // This is the correct way
    parser = new DOMParser()
    e = parser.parseFromString(responsecontent, "text/html");
    table = e.getElementsByClassName("main-info-pnl")[0].children[1].children[0]
    date = table.children[3].children[1].innerText
    time = table.children[4].children[1].innerText`
but this will break the old response sheet
add a if statement to check if first child contains text "JEE April 2024" or anything else and accordingly select child

**Comment by timepassuser** [comment]
Um.. already did saw too late, so closing
