### ISSUE TITLE
My result not showing

### ISSUE THREAD

**Issue by Anubhavtyagi120** [timepassuser/Jee-Mains-Marks-Calculator#9]
https://cdn3.digialm.com//per/g28/pub/2083/touchstone/AssessmentQPHTMLMode1//2083O24112/2083O24112S3D23763/17123941378391341/UP091243303_2083O24112S3D23763E1.htmlv

**Comment by Aedon** [comment]
Bhai tumhari link se v hatao

**Comment by timepassuser** [comment]
As aedon said, remove v from the link at the end

**Comment by Anubhavtyagi120** [comment]
Thnx
